config/routes.rb
Rails.application.routes.draw do
  resources :sales
  devise_for :users
  resources :ads
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/ad.rb
class Ad < ApplicationRecord

    has_many_attached :images

    belongs_to :user

    has_one :sale, dependent: :destroy

    validates :title, presence: true
    validates :category, presence: true
    validates :state, presence: true
    validates :images, presence: true
    validates :description, presence: true, length: { minimum: 15 }
    validates :price, presence: true
    validates :shipment, presence: true
    validates :city, presence: true

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/sale.rb
class Sale < ApplicationRecord
  after_create :add_sale
  after_destroy :reset_sale

  belongs_to :ad

  belongs_to :user

  def add_sale
    @ad = Ad.find(ad_id)
    @ad.update_attribute(:sold, true)
  end

  def reset_sale
    @ad = Ad.find(ad_id)
    @ad.update_attribute(:sold, false)
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_one_attached :avatar

  has_many :ads, dependent: :destroy

  has_many :sale, dependent: :destroy

  validates :name, presence: true
  validates :email, presence: true


  def avatar_size
    avatar.variant(resiez: "150x150!").processed
  end
  

end

app/controllers/Users/devise_controller.rb
class Users::DeviseController < ApplicationController
    class Responder < ActionController::Responder
        def to_turbo_stream
        controller.render(options.merge(formats: :html))
        rescue ActionView::MissingTemplate => error
        if get?
            raise error
        elsif has_errors? && default_action
            render rendering_options.merge(formats: :html, status: :unprocessable_entity)
        else
            redirect_to navigation_location
        end
        end
    end

    self.responder = Responder
    respond_to :html, :turbo_stream
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  before_action :set_ad, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ create ]

  # GET /ads or /ads.json
  def index
    @query = Ad.ransack(params[:q])
    @ads = @query.result(distinct: true).where("sold = ?", false)

    if turbo_frame_request?
      render partial: "ads", locals: { ads: @ads }
    else
      render :index
    end
  
  end

  # GET /ads/1 or /ads/1.json
  def show
    @sale = Sale.new
    @sale.user = current_user
    @sale.ad = @ad
  end

  # GET /ads/new
  def new
    @ad = Ad.new
  end

  # GET /ads/1/edit
  def edit
  end

  # POST /ads or /ads.json
  def create
    @ad = Ad.new(ad_params)
    @ad.user = current_user
    # @sale = Sale.new
    # @sale.user = current_user
    # @sale.ad = @ad

    respond_to do |format|
      if @ad.save
        format.html { redirect_to ad_url(@ad), notice: "Ad was successfully created." }
        format.json { render :show, status: :created, location: @ad }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ads/1 or /ads/1.json
  def update

    respond_to do |format|
      if @ad.update(ad_params)
        format.html { redirect_to ad_url(@ad), notice: "Ad was successfully updated." }
        format.json { render :show, status: :ok, location: @ad }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ads/1 or /ads/1.json
  def destroy
    @ad.destroy

    respond_to do |format|
      format.html { redirect_to root_path, notice: "Ad was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ad
      @ad = Ad.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ad_params
      params.require(:ad).permit(:title, :category, :state, :description, :price, :city, :shipment, images: [])
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :configure_sign_up_params, only: [:create], if: :devise_controller?
    before_action :configure_account_update_params, only: [:update], if: :devise_controller?
    before_action :set_query

    def set_query
        @query = Ad.ransack(params[:q])
        @ads = @query.result(distinct: true).where("sold = ?", false)
    end

    protected

    
    # If you have extra params to permit, append them to the sanitizer.
    def configure_sign_up_params
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :sex, :role, :city])
    end

    # If you have extra params to permit, append them to the sanitizer.
    def configure_account_update_params
        devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email, :sex, :role, :city, :avatar, :avatar_cache, :remove_avatar])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
    
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ create ]
  before_action :authenticate_admin, only: %i[ index ]

  # GET /sales or /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1 or /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales or /sales.json
  def create
    @sale = Sale.new(sale_params)
    @sale.user = current_user
    @email = params[:email]
    puts @email.inspect

    respond_to do |format|
      if @sale.save
        AdMailer.sold(@email).deliver_now
        format.html { redirect_to sale_url(@sale), notice: "Sale was successfully created." }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1 or /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to sale_url(@sale), notice: "Sale was successfully updated." }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1 or /sales/1.json
  def destroy
    @sale.destroy

    respond_to do |format|
      format.html { redirect_to root_path, notice: "Sale was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sale_params
      params.require(:sale).permit(:ad_id, :user_id)
    end

    def authenticate_admin
      redirect_to root_path, notice: "Access retricted." unless current_user.admin 
    end
end

app/helpers/ads_helper.rb
module AdsHelper
    def state_of_sale(sale)
        if sale
            "sold ✅"
        else
            "on sale 🔄"
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/ads/_ad.html.erb
<div id= " <%= dom_id ad %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= ad.title %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Category:</strong>
    <%= ad.category %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">State:</strong>
    <%= ad.state %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Images:</strong>
    <% ad.images.each do |image| %>
      <%= image_tag(image, class:"max-w-xs min-h-min") %>
    <% end %> 
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= ad.description %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Price:</strong>
    <%= ad.price %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">City:</strong>
    <%= ad.city %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Shipment:</strong>
    <%= ad.shipment %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this ad", ad, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this ad', edit_ad_path(ad), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/ads/_index.html.erb
<section class="bg-white dark:bg-gray-900">
    <div class="py-8 px-4 mx-auto max-w-screen-xl lg:py-16 lg:px-6 ">
        <div class="mx-auto max-w-screen-sm text-center mb-8 lg:mb-16">
            <h2 class="mb-4 text-4xl tracking-tight font-extrabold text-gray-900 dark:text-white"><%= pluralize(@ads.count, "Ads")%></h2>
        </div> 
        <div class="grid gap-8 mb-6 lg:mb-16 md:grid-cols-2">
            <% @ads.each do |ad| %>
                <div class="items-center bg-gray-50 rounded-lg shadow sm:flex dark:bg-gray-800 dark:border-gray-700">
                    <a href="#">
                        <%= image_tag(ad.images[0], class:"w-60 h-56 rounded-lg sm:rounded-none sm:rounded-l-lg") if ad.images.present? %>
                    </a>
                    <div class="p-5">
                        <h3 class="text-xl font-bold tracking-tight text-gray-900 dark:text-white">
                            <%= ad.title %>
                        </h3>
                        <h3 class="text-xl font-bold tracking-tight text-gray-900 dark:text-white">
                            <%= ad.price %>
                        </h3>
                        <span class="text-gray-500 dark:text-gray-400"><%= ad.category %></span>
                        <p class="mt-3 mb-4 font-light text-gray-500 dark:text-gray-400"><%= link_to 'Show', ad_path(ad.id), class:"focus:outline-none text-white bg-green-700 hover:bg-green-800 focus:ring-4 focus:ring-green-300 font-medium rounded-lg text-sm px-1 py-2.5 ml-10 mb-2 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800" %></p>
                    </div>
                </div>
            <% end %>  
        </div>  
    </div>
</section>

app/views/ads/_search_form.html.erb
<div class="flex flex-col items-center justify-center">
    <div class="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700">
        <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
            <h1 class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
                Filter
            </h1>
            <%= search_form_for(@query, url: :ads, data: {turbo_frame: "ads", turbo_action: "advance"} ) do |f| %>
                <form class=" flex flex-row space-y-4 md:space-y-6">
                    <%= f.text_field :title_cont, class:"mb-2 bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500", placeholder: "Title" %>
                
                    <%= f.text_field :category_cont, class:" mb-2 bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500", placeholder: "Category" %>
                
                    <%= f.text_field :city_cont, class:" mb-2 bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500", placeholder: "City" %>
                
                    <%= f.text_field :price_gteq, class:" mb-2 bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500", placeholder: "Price min" %>

                    <%= f.text_field :price_lteq, class:" mb-2 bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500", placeholder: "Price max" %>

                    <%= f.submit "Search", class:"text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800" %>
                    <%= link_to "Reset", ads_path, class:"py-2.5 px-5 mr-2 mb-2 text-sm font-medium text-blue-600 focus:outline-none bg-white rounded-lg border border-blue-600 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700"%>
                </form>
            <% end %>
        </div>
    </div>
</div>

app/views/ads/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing ad</h1>

  <%= render "form", ad: @ad %>

  <%= link_to "Show this ad", @ad, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to ads", ads_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/ads/index.html.erb
<div class="w-full">

  <%= render 'search_form' %>

  <%= turbo_frame_tag "ads" do %>
    <%= render 'ads/index' %>
  <% end %>

</div>

app/views/ads/new.html.erb
<div class="mx-auto md:w-2/3 w-full">

  <h1 class="font-bold text-4xl text-center">Déposer une annonce</h1>

  <%= render "form", ad: @ad %>

  <%= link_to 'Back to ads', ads_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/ads/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    
    <%= render @ad %> 

    <% if current_user == @ad.user %>
      <%= link_to 'Edit this ad', edit_ad_path(@ad), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      <div class="inline-block ml-2">
        <%= button_to 'Destroy this ad', ad_path(@ad), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
      </div>  
    <% end %>

    <% if current_user!=@ad.user && (@ad.sold == false )%>

      <div class="inline-block m-2">
        <%= render "sales/form", sale: @sale, email: @ad.user.email %>
      </div>

    <% end %>

    <div class="inline-block m-2">
      <%= link_to 'Back to ads', ads_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Leboncoincoin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://unpkg.com/flowbite@1.5.2/dist/flowbite.min.css" />
  </head>

  <body>
    <main class="container mx-auto mt-10">
      <%= render 'shared/flash' %>
      <%= render 'shared/navbar' %>
      <%= yield %>
    </main>
    <script src="https://unpkg.com/flowbite@1.5.2/dist/flowbite.js"></script>
  </body>
</html>

app/views/pages/home.html.erb
<%= render 'ads/search_form' %>

<%= turbo_frame_tag "ads" do %>
    <%= render 'ads/index'%> 
<% end %>

app/views/sales/_form.html.erb
<%= form_with(model: @sale, class: "contents") do |form| %>
  <div class="my-5">
    <%= form.hidden_field :user_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
  <%= form.hidden_field :ad_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <%= hidden_field_tag :email, value = email %>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer"  %>
  </div>
<% end %>

app/views/sales/_index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Sales</h1>
    <%= link_to 'New sale', new_sale_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="sales" class="min-w-full">
    <%= render @sales %>
  </div>
</div>

app/views/sales/_sale.html.erb
<div id="<%= dom_id sale %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Ad:</strong>
      <%= sale.ad.title %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">User:</strong>
    <%= sale.user.name %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this sale", sale, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Show ad", ad_path(sale.ad_id), class: "focus:outline-none text-white bg-green-700 hover:bg-green-800 focus:ring-4 focus:ring-green-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/sales/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing sale</h1>

  <%= render "form", sale: @sale %>

  <%= link_to "Show this sale", @sale, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to sales", sales_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/sales/index.html.erb
<div class="w-full">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Sales</h1>
    <%= link_to 'New sale', new_sale_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="sales" class="min-w-full">
    <%= render @sales %>
  </div>
</div>

app/views/sales/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New sale</h1>

  <%= render "form", sale: @sale %>

  <%= link_to 'Back to sales', sales_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/sales/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">

    <%= render @sale %>

    <div class="inline-block ml-2">
      <%= link_to 'Back to sales', edit_user_registration_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    </div>  
  </div>
</div>

app/views/shared/_flash.html.erb
<% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
<% end %>

<% if alert.present? %>
    <p class="py-2 px-3 bg-red-50 mb-5 text-red-500 font-medium rounded-lg inline-block" id="alert"><%= alert %></p>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="bg-white border-gray-200 px-2 sm:px-4 py-2.5 rounded dark:bg-gray-900">
    <div class="container flex flex-wrap justify-between items-center mx-auto">
        <div class="flex items-center">
            <%= link_to 'Leboncoincoin', root_path, class:"self-center text-xl font-semibold whitespace-nowrap dark:text-white"  %>
        </div>

        <div class=" justify-between items-center w-full md:flex md:w-auto md:order-1" id="mobile-menu-2">
            <ul class="flex flex-col p-4 mt-4 bg-gray-50 rounded-lg border border-gray-100 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
                <li>
                    <%= link_to "Add an ad", new_ad_path, class:"mb-4 text-4xl  tracking-tight font-extrabold text-gray-900 dark:text-white" %>
                </li>
            </ul>
        </div> 

        <% if user_signed_in? %>
            <div class="flex items-center md:order-2">
                    <button type="button" class="flex mr-3 text-sm bg-gray-800 rounded-full md:mr-0 focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600" id="user-menu-button" aria-expanded="false" data-dropdown-toggle="user-dropdown" data-dropdown-placement="bottom">
                        <span class="sr-only">Open user menu</span>
                        <% if current_user.avatar.attached? %>
                            <%= image_tag(current_user.avatar, class:"w-8 h-8 rounded-full")%>
                        <% else %>
                            <img class="w-8 h-8 rounded-full" src="https://www.librerentier.com/wp-content/plugins/schema-and-structured-data-for-wp//admin_section/images/default_user.jpg" alt="">
                        <% end %>
                    </button>
                    <!-- Dropdown menu -->
                    <div class="z-50 my-4 text-base list-none bg-white rounded divide-y divide-gray-100 shadow dark:bg-gray-700 dark:divide-gray-600 block hidden" id="user-dropdown" style="position: absolute; inset: 0px auto auto 0px; margin: 0px; transform: translate3d(661px, 82px, 0px);" data-popper-reference-hidden="" data-popper-escaped="" data-popper-placement="bottom">
                        <div class="py-3 px-4">
                            <span class="block text-sm text-gray-900 dark:text-white"><%= current_user.name%></span>
                            <span class="block text-sm font-medium text-gray-500 truncate dark:text-gray-400"><%= current_user.email%></span>
                        </div>
                        <ul class="py-1" aria-labelledby="user-menu-button">
                            <li>
                                <%= link_to "Profil", edit_user_registration_path, class:"block py-2 px-4 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white"  %>
                            </li>
                            <% if current_user.admin %>
                                <li>
                                    <%= link_to "Ads", ads_path, class:"block py-2 px-4 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white"  %>
                                </li>
                                <li>
                                    <%= link_to "Sales", sales_path, class:"block py-2 px-4 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white"  %>
                                </li>
                            <% end %>
                            <li>
                                <%= button_to "Sign_out", destroy_user_session_path, method: :delete, class:"block py-2 px-4 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white"  %>
                            </li>
                        </ul>
                    </div>
                    <button data-collapse-toggle="mobile-menu-2" type="button" class="inline-flex items-center p-2 ml-1 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="mobile-menu-2" aria-expanded="false">
                        <span class="sr-only">Open main menu</span>
                        <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
                    </button>
                </div>
        <% else %>
            <div class="flex flex-row items-center">
                <div class="mx-2">
                    <%= link_to "S'inscrire", new_user_registration_path, class:"self-center text-xl font-semibold whitespace-nowrap dark:text-white" %> 
                </div>
                <div class="mx-2">
                    <%= link_to "Se connecter", new_user_session_path, class:"self-center text-xl font-semibold whitespace-nowrap dark:text-white" %> 
                </div>
            </div>
        <% end %>
    </div>
</nav>